import { mkdir, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'
import { scanMcpTarget } from '../scanners/mcp-scanner.js'
import { scanRepository } from '../scanners/repo-scanner.js'
import { calculateScorecard, reportOutputPaths } from '../scoring.js'
import type { AuditReport, McpScanResult, RepoSignals } from '../types.js'
import { renderJsonReport } from '../reporters/json.js'
import { renderMarkdownReport, renderMcpMarkdown } from '../reporters/markdown.js'

export interface GenerateAgentPackResult {
  report: AuditReport
  mcpResults: McpScanResult[]
  files: string[]
}

export interface GenerateAgentPackOptions {
  llmSummary?: string
}

export async function generateAgentPack(
  repoPath: string,
  outDir: string,
  options: GenerateAgentPackOptions = {}
): Promise<GenerateAgentPackResult> {
  const signals = await scanRepository(repoPath)
  const mcpResults = await scanDetectedMcpTargets(repoPath, signals)
  const report = calculateScorecard(signals, mcpResults)
  const files = new Set<string>()

  await mkdir(join(outDir, 'skills'), { recursive: true })
  await writePackFile(outDir, 'AGENTS.md', renderAgentsFile(report, signals, options.llmSummary), files)
  await writePackFile(outDir, 'repo-map.md', renderRepoMap(report, signals), files)
  await writePackFile(outDir, 'skills/agent-setup.md', renderAgentSetupSkill(signals), files)
  await writePackFile(outDir, 'skills/repo-audit.md', renderRepoAuditSkill(report), files)
  await writePackFile(outDir, 'skills/mcp-safety.md', renderMcpSafetySkill(mcpResults), files)
  await writePackFile(outDir, 'promptfoo.yaml', renderPromptfooConfig(report), files)
  await writePackFile(outDir, 'mcp-review.md', renderMcpMarkdown(mcpResults), files)
  if (options.llmSummary) {
    await writePackFile(outDir, 'skills/llm-synthesis.md', renderLlmSummarySkill(options.llmSummary), files)
  }

  const outputPaths = reportOutputPaths(outDir)
  await writePackFile(outDir, relative(outDir, outputPaths.markdown), renderMarkdownReport(report, mcpResults), files)
  await writePackFile(outDir, relative(outDir, outputPaths.json), renderJsonReport(report), files)

  return {
    report,
    mcpResults,
    files: [...files].sort((a, b) => a.localeCompare(b))
  }
}

export async function scanDetectedMcpTargets(repoPath: string, signals: RepoSignals): Promise<McpScanResult[]> {
  const results: McpScanResult[] = []

  for (const relativePath of signals.mcpConfigFiles) {
    results.push(await scanMcpTarget(join(repoPath, relativePath)))
  }

  return results
}

async function writePackFile(outDir: string, relativePath: string, content: string, files: Set<string>): Promise<void> {
  const normalizedPath = relativePath.replaceAll('\\', '/')
  const destination = join(outDir, normalizedPath)
  await mkdir(join(destination, '..'), { recursive: true })
  await writeFile(destination, content, 'utf8')
  files.add(normalizedPath)
}

function renderAgentsFile(report: AuditReport, signals: RepoSignals, llmSummary?: string): string {
  const optionalSummary = llmSummary ? `\n## Optional LLM Synthesis\n\n${llmSummary}\n` : ''

  return `# Agent Operating Instructions

This pack was generated by OpsCanon for \`${report.repo.name}\`.

## Start Here

1. Read \`repo-map.md\` before editing.
2. Follow setup commands exactly as documented in the repository.
3. Run the available checks before claiming work is complete.
4. Keep secrets out of source control and generated reports.

## Detected Commands

- Test: ${formatCommands(signals.testCommands)}
- Build: ${formatCommands(signals.buildCommands)}
- Lint: ${formatCommands(signals.lintCommands)}

## Agent Rules

- Prefer machine-readable interfaces when available: CLI, API, OpenAPI, or MCP.
- If a command needs credentials, use environment variables and never write token values to files.
- If MCP tools are present, inspect \`mcp-review.md\` before enabling them.
- If behavior changes, add or update evals in \`promptfoo.yaml\`.

## Current OpsCanon Repo Readiness Score

Overall score: ${report.overallScore}/100
${optionalSummary}
`
}

function renderRepoMap(report: AuditReport, signals: RepoSignals): string {
  return `# Repo Map

## Summary

- Repository: ${report.repo.name}
- Files scanned: ${signals.filesScanned}
- Languages: ${formatList(signals.languages)}
- Manifests: ${formatList(signals.manifests)}

## Documentation

- Docs files: ${formatList(signals.docsFiles)}
- Agent instructions present: ${signals.hasAgentInstructions ? 'yes' : 'no'}
- Setup docs present: ${signals.hasSetupDocs ? 'yes' : 'no'}
- Usage docs present: ${signals.hasUsageDocs ? 'yes' : 'no'}

## Machine Interfaces

- CLI entrypoints: ${formatList(signals.cliEntrypoints)}
- OpenAPI files: ${formatList(signals.openApiFiles)}
- MCP config files: ${formatList(signals.mcpConfigFiles)}

## Verification

- CI files: ${formatList(signals.ciFiles)}
- Test commands: ${formatCommands(signals.testCommands)}
- Build commands: ${formatCommands(signals.buildCommands)}
- Lint commands: ${formatCommands(signals.lintCommands)}
`
}

function renderAgentSetupSkill(signals: RepoSignals): string {
  return `# Agent Setup Skill

Use this skill when an AI agent needs to work in this repository.

1. Inspect the repo map.
2. Install dependencies using the package manager implied by: ${formatList(signals.manifests)}.
3. Run tests with: ${formatCommands(signals.testCommands)}.
4. If no test command is available, add one before making risky changes.
5. Use env placeholders from: ${formatList(signals.envExampleFiles)}.
`
}

function renderRepoAuditSkill(report: AuditReport): string {
  const fixes = report.topFixes.length > 0
    ? report.topFixes.map((fix, index) => `${index + 1}. ${fix.title}: ${fix.recommendation}`).join('\n')
    : 'No high-priority fixes detected.'

  return `# Repo Audit Skill

Use this skill before asking an agent to make non-trivial edits.

Current score: ${report.overallScore}/100

## Priority Fixes

${fixes}
`
}

function renderMcpSafetySkill(results: McpScanResult[]): string {
  const lines = results.length > 0
    ? results.map((result) => `- ${result.target}: risk ${result.riskScore}/100`).join('\n')
    : '- No MCP targets detected.'

  return `# MCP Safety Skill

Use this skill before enabling or calling MCP tools from this repository.

${lines}

Rules:

1. Do not store direct token values in MCP config.
2. Prefer fixed executables over shell startup commands.
3. Require clear tool descriptions and JSON input schemas.
4. Review tool side effects before granting write access.
`
}

function renderLlmSummarySkill(summary: string): string {
  return `# LLM Synthesis

This optional synthesis was generated only because \`OPENAI_API_KEY\` was present and the caller requested \`--llm\`.

${summary}
`
}

function renderPromptfooConfig(report: AuditReport): string {
  return `description: OpsCanon repo readiness evals for ${report.repo.name}
prompts:
  - "Using only this repo's docs, explain how an AI agent should install, test, and safely operate the project."
  - "List the machine-readable interfaces available to agents and identify missing CLI/API/MCP surfaces."
  - "Identify MCP or secret-handling risks and propose concrete fixes."
providers:
  - id: echo
tests:
  - vars: {}
    assert:
      - type: contains
        value: "agent"
      - type: not-contains
        value: "sk-"
`
}

function formatList(values: string[]): string {
  return values.length > 0 ? values.map((value) => `\`${value}\``).join(', ') : 'none detected'
}

function formatCommands(values: string[]): string {
  return values.length > 0 ? values.map((value) => `\`${value}\``).join(', ') : 'none detected'
}
