name: Publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run npm publish without publishing.
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
      - name: Dry run
        if: ${{ inputs.dry-run == 'true' }}
        run: |
          npm run test:coverage
          npm run typecheck
          npm run build
          npm pack --dry-run
      - name: Publish
        if: ${{ inputs.dry-run == 'false' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance
